apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-kr5k
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0053-tenant/ci10t-786-0053-app/devfile-sample-kr5k@sha256:0e97a254321e386753f0d2397053ac8eb1676b4a1c79a002db086232bfbf3a2f
        name: my-nodejs
        resources: {}
status: {}
